CREATE TABLE IF NOT EXISTS contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code TEXT,
  customer_name TEXT NOT NULL,
  business_number TEXT,
  department_name TEXT,
  recipient_name TEXT NOT NULL,
  recipient_title TEXT,
  recipient_email TEXT,
  recipient_phone TEXT,
  preferred_channel TEXT NOT NULL DEFAULT 'EMAIL',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  memo TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_contacts_customer
ON contacts(customer_code, customer_name);

CREATE INDEX IF NOT EXISTS idx_contacts_status
ON contacts(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS closing_companies (
  company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  customer_code TEXT,
  owner_name TEXT,
  deadline_day INTEGER,
  closing_month TEXT NOT NULL,
  confirmed_amount NUMERIC(15, 2) DEFAULT 0,
  tax_amount NUMERIC(15, 2) DEFAULT 0,
  progress INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'WAITING',
  reason TEXT,
  memo TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_closing_companies_month_status
ON closing_companies(closing_month, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS todo_items (
  todo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL DEFAULT 'TODO',
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT NOT NULL DEFAULT 'MEDIUM',
  status TEXT NOT NULL DEFAULT 'OPEN',
  due_date DATE,
  reminder_at TIME,
  completed_at TIMESTAMPTZ,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_todo_items_due_status
ON todo_items(due_date, status, item_type);

CREATE TABLE IF NOT EXISTS app_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  message TEXT NOT NULL,
  meta_json JSONB,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_events_target
ON app_events(target_type, target_id, created_at DESC);

CREATE TABLE IF NOT EXISTS backup_history (
  backup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_type TEXT NOT NULL DEFAULT 'MANUAL',
  s3_bucket TEXT,
  s3_key TEXT,
  file_name TEXT,
  size_bytes BIGINT DEFAULT 0,
  message TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backup_history_created
ON backup_history(created_at DESC);
