CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name VARCHAR(50),
  role TEXT NOT NULL DEFAULT 'USER',
  department_name TEXT,
  email TEXT,
  phone TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_status
ON users(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS contacts (
  contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code TEXT,
  customer_name TEXT NOT NULL,
  business_number TEXT,
  department_name TEXT,
  recipient_name TEXT NOT NULL,
  recipient_title TEXT,
  recipient_email TEXT,
  recipient_phone TEXT,
  preferred_channel TEXT NOT NULL DEFAULT 'EMAIL',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  memo TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_contacts_customer
ON contacts(customer_code, customer_name);

CREATE INDEX IF NOT EXISTS idx_contacts_status
ON contacts(status, updated_at DESC);

CREATE TABLE IF NOT EXISTS closing_companies (
  company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  customer_code TEXT,
  owner_name TEXT,
  deadline_day INTEGER,
  closing_month TEXT NOT NULL,
  confirmed_amount NUMERIC(15, 2) DEFAULT 0,
  tax_amount NUMERIC(15, 2) DEFAULT 0,
  progress INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'WAITING',
  reason TEXT,
  memo TEXT,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_closing_companies_month_status
ON closing_companies(closing_month, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS todo_items (
  todo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_type TEXT NOT NULL DEFAULT 'TODO',
  title TEXT NOT NULL,
  description TEXT,
  priority TEXT NOT NULL DEFAULT 'MEDIUM',
  status TEXT NOT NULL DEFAULT 'OPEN',
  due_date DATE,
  reminder_at TIME,
  completed_at TIMESTAMPTZ,
  created_by TEXT,
  updated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_todo_items_due_status
ON todo_items(due_date, status, item_type);

CREATE TABLE IF NOT EXISTS app_events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  target_type TEXT,
  target_id TEXT,
  message TEXT NOT NULL,
  meta_json JSONB,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_app_events_target
ON app_events(target_type, target_id, created_at DESC);

CREATE TABLE IF NOT EXISTS backup_history (
  backup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_type TEXT NOT NULL DEFAULT 'MANUAL',
  s3_bucket TEXT,
  s3_key TEXT,
  file_name TEXT,
  size_bytes BIGINT DEFAULT 0,
  message TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_backup_history_created
ON backup_history(created_at DESC);

-- Shared master data and historical work records migrated from local SQLite.
-- Local file paths and temporary workspace snapshots intentionally remain on each PC.
CREATE TABLE IF NOT EXISTS customers (
  customer_code TEXT PRIMARY KEY,
  customer_name TEXT NOT NULL,
  business_number TEXT,
  tax_status TEXT NOT NULL DEFAULT 'UNKNOWN',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  memo TEXT,
  closing_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  product_code TEXT PRIMARY KEY,
  product_name TEXT NOT NULL,
  unit TEXT NOT NULL DEFAULT 'EA',
  unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
  currency TEXT NOT NULL DEFAULT 'KRW',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales_uploads (
  upload_key TEXT PRIMARY KEY,
  file_name TEXT NOT NULL,
  closing_month TEXT NOT NULL,
  uploaded_department_code TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'UPLOADED',
  memo TEXT
);

CREATE TABLE IF NOT EXISTS sales (
  sale_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upload_key TEXT NOT NULL REFERENCES sales_uploads(upload_key) ON DELETE CASCADE,
  row_no INTEGER NOT NULL,
  transaction_date DATE,
  raw_customer_name TEXT,
  raw_product_name TEXT,
  customer_code TEXT REFERENCES customers(customer_code),
  product_code TEXT REFERENCES products(product_code),
  quantity NUMERIC(15, 3),
  unit_price NUMERIC(15, 2),
  sales_amount NUMERIC(15, 2),
  validation_status TEXT NOT NULL DEFAULT 'PENDING',
  review_status TEXT NOT NULL DEFAULT 'WAITING',
  owner_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(upload_key, row_no)
);

CREATE TABLE IF NOT EXISTS validation_issues (
  issue_key TEXT PRIMARY KEY,
  upload_key TEXT NOT NULL REFERENCES sales_uploads(upload_key) ON DELETE CASCADE,
  row_no INTEGER,
  error_type TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'WARNING',
  message TEXT NOT NULL,
  expected_value TEXT,
  actual_value TEXT,
  assigned_department_code TEXT,
  status TEXT NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  resolved_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS report_templates (
  template_key TEXT PRIMARY KEY,
  report_name TEXT NOT NULL,
  report_type TEXT NOT NULL,
  description TEXT,
  default_format TEXT NOT NULL DEFAULT 'XLSX',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reports (
  report_key TEXT PRIMARY KEY,
  template_key TEXT REFERENCES report_templates(template_key),
  upload_key TEXT REFERENCES sales_uploads(upload_key),
  report_name TEXT NOT NULL,
  report_type TEXT,
  closing_month TEXT,
  total_quantity NUMERIC(15, 3) NOT NULL DEFAULT 0,
  total_sales_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
  output_format TEXT NOT NULL DEFAULT 'XLSX',
  files_json JSONB,
  tags_json JSONB,
  options_json JSONB,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'GENERATED',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS message_templates (
  template_key TEXT PRIMARY KEY,
  template_name TEXT NOT NULL,
  channel TEXT NOT NULL DEFAULT 'EMAIL',
  subject_template TEXT,
  body_template TEXT NOT NULL,
  tone TEXT NOT NULL DEFAULT 'COOPERATIVE',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_history (
  email_key TEXT PRIMARY KEY,
  package_name TEXT NOT NULL,
  upload_key TEXT REFERENCES sales_uploads(upload_key),
  closing_month TEXT,
  customer_code TEXT,
  customer_name TEXT,
  recipient_email TEXT,
  recipient_phone TEXT,
  channel TEXT NOT NULL DEFAULT 'EMAIL',
  subject TEXT,
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'READY',
  sent_checked_at TIMESTAMPTZ,
  memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cloud_migration_runs (
  migration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by TEXT NOT NULL,
  summary_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
